### ISSUE TITLE
Question about the data

### ISSUE THREAD

**Issue by silt99** [cialab/deepfocus#1]
Hello,
i'd downloaded the training data but i do not know how to interpret the values of Y: they are integers that go from 0 to 9, but in the paper it is mention that the clasification is 0 or 1 (-0.5 to 0.5 are 0 and anyother value is 1). Also, i would like to ask for the validation dataset (21600 patches) if possible. 
Lastly, if possible i would want to know the correspondece between blur and not blur patches.

Thank you very much!
Best regards.

**Comment by senaras** [comment]
the values are  [-0.5,-1.5, -2 ,-2.5 ,-3 ,0 ,0.5 , 1.5, 2, 2.5, 3].

**Comment by senaras** [comment]
Since, I moved to another company, currently I do not have the validation dataset. I will try to reach my colleagues  and find the validation dataset.

**Comment by silt99** [comment]
Thank you very much for everything. I really appreciate your help.
